### PR TITLE
add TARGET_HAS_MEMFD_BACKPORT conditional 

### PR DESCRIPTION
**Pull request by Nesquirt**

### CODE REVIEW

**Comment by Nesquirt** [comment]
on vayu without this doesn't build

**Comment by hpnightowl** [comment]
oh cool i will partially revert the cleanup then

**Comment by hpnightowl** [comment]
@Nesquirt can you check if all good also ping me up will close this if all good.

**Comment by Nesquirt** [comment]
@hpnightowl yes sir, il clone and i told u

**Comment by Nesquirt** [comment]
@hpnightowl and man i've also an other issue,i'll send a pr when i'll work

**Comment by hpnightowl** [comment]
okie Cool ! @Nesquirt Thanks :) Nice Work ! Closing this PR then till then.

**Comment by Nesquirt** [comment]
@hpnightowl now it build,thanks man.
See my other PR there are some duplicate path

**Pull request closed without merging**
